spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

  application:
    name: namij

  datasource:
      url: jdbc:mysql://localhost:3306/nami
      username: ${db_user:user}
      password: ${db_password:password}
  flyway:
    enabled: true
server:
  port: 9090
email:
  username: ugo
  password: 4MpybH^g&rsmOg2
  host: 127.0.0.1
  port: 3143
  mailbox: INBOX
  pollRate: 60000
  scheme: imap
pebble:
  exposeRequestAttributes: true